// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnxzducfsoioolnntshv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJueHpkdWNmc29pb29sbm50c2h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzQyODcsImV4cCI6MjA2NTkxMDI4N30.hkJz83aRKbvqFZa8x-4dwsXELDqDWwFUmY3pNh1Ir5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);